pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - ci/travis
init:
- git config --global core.autocrlf input
cache:
- packages -> src\**\packages.config, tests\**\packages.config
- tools -> setup.cake, tools\packages.config
build_script:
- ps: .\build.ps1 -Configuration Release -Verbosity Verbose -Target AppVeyor
test: off

skip_commits:
  files:
    - '**/*.md'
    - '*.vsext'
    - '*.userprefs'
    - '*.editorconfig'
    - build.sh
